//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272Group11Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VotingSystemProjectEntities2 : DbContext
    {
        public VotingSystemProjectEntities2()
            : base("name=VotingSystemProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<CandidatePosition> CandidatePositions { get; set; }
        public virtual DbSet<CityOrTown> CityOrTowns { get; set; }
        public virtual DbSet<Election> Elections { get; set; }
        public virtual DbSet<NationalResult> NationalResults { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PartyImage> PartyImages { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<ProvincialResult> ProvincialResults { get; set; }
        public virtual DbSet<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffPosition> StaffPositions { get; set; }
        public virtual DbSet<Suburb> Suburbs { get; set; }
        public virtual DbSet<Voter> Voters { get; set; }
        public virtual DbSet<VotingStation> VotingStations { get; set; }
    }
}
