//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272Group11Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyImage
    {
        public int partyID { get; set; }
        public byte[] PartyPicture { get; set; }
        public byte[] PartyLeaderPicture { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
