//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272Group11Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.Candidates = new HashSet<Candidate>();
            this.NationalResults = new HashSet<NationalResult>();
            this.ProvincialResults = new HashSet<ProvincialResult>();
        }
    
        public int PartyID { get; set; }
        public string PartyName { get; set; }
        public string PartyAccronym { get; set; }
        public string PartyStreetAddress { get; set; }
        public string PartyTelephone { get; set; }
        public string PartyWebsite { get; set; }
        public string PartyEmail { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityOrTownID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual CityOrTown CityOrTown { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NationalResult> NationalResults { get; set; }
        public virtual Province Province { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual PartyImage PartyImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvincialResult> ProvincialResults { get; set; }
    }
}
