//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272Group11Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingStation
    {
        public int VotingStationID { get; set; }
        public string VotingStationName { get; set; }
        public decimal VotingStationLatitude { get; set; }
        public decimal VotingStationLongitude { get; set; }
        public System.DateTime VotingStationOpeningTime { get; set; }
        public System.DateTime VotingStationClosingTime { get; set; }
        public string VotingStationStreetAddress { get; set; }
        public Nullable<int> SuburbID { get; set; }
    
        public virtual Suburb Suburb { get; set; }
    }
}
